# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
