# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_form', '0002_auto_20170425_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('reason', models.TextField(help_text='Enter reason here...', max_length=1024)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_form.Doctor')),
            ],
        ),
    ]
