# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_form', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[(1, '8:00-9:00'), (2, '9:00-10:00'), (3, '10:00-11:00'), (4, '11:00-12:00'), (5, '12:00-13:00'), (6, '13:00-14:00'), (7, '14:00-15:00'), (8, '15:00-16:00')], default=1, max_length=32),
        ),
    ]
