# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_form', '0005_auto_20170425_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(default=222, help_text='Enter your phone number here...', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(help_text='Enter your full name here...', max_length=256),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(help_text='Describe details of your reason here...', max_length=1024),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(help_text='Enter your subject here...', max_length=256),
        ),
    ]
